services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: etl_ml
    ports:
      - "5437:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
      